export const filelist = [
  "accounts/(DEPRECATED) Identity proofs",
  "accounts/Block account",
  "accounts/Check relationships to other accounts",
  "accounts/Feature account on your profile",
  "accounts/Find familiar followers",
  "accounts/Follow account",
  "accounts/Get account",
  "accounts/Get account’s featured tags",
  "accounts/Get account’s followers",
  "accounts/Get account’s following",
  "accounts/Get account’s statuses",
  "accounts/Get lists containing this account",
  "accounts/Lookup account ID from Webfinger address",
  "accounts/Mute account",
  "accounts/Register an account",
  "accounts/Remove account from followers",
  "accounts/Search for matching accounts",
  "accounts/Set private note on profile",
  "accounts/Unblock account",
  "accounts/Unfeature account from profile",
  "accounts/Unfollow account",
  "accounts/Unmute account",
  "accounts/Update account credentials",
  "accounts/Verify account credentials",
  "announcements/Add a reaction to an announcement",
  "announcements/Dismiss an announcement",
  "announcements/Remove a reaction from an announcement",
  "announcements/View all announcements",
  "apps/Create an application",
  "apps/Verify your app works",
  "blocks/View blocked users",
  "bookmarks/View bookmarked statuses",
  "conversations/Mark a conversation as read",
  "conversations/Remove a conversation",
  "conversations/View all conversations",
  "custom_emojis/View all custom emoji",
  "directory/View profile directory",
  "domain_blocks/Block a domain",
  "domain_blocks/Get domain blocks",
  "domain_blocks/Unblock a domain",
  "emails/Resend confirmation email",
  "endorsements/View currently featured profiles",
  "favourites/View favourited statuses",
  "featured_tags/Feature a tag",
  "featured_tags/Unfeature a tag {unfeature}",
  "featured_tags/View suggested tags to feature",
  "featured_tags/View your featured tags",
  "filters/Add a keyword to a filter v2",
  "filters/Add a status to a filter group v2",
  "filters/Create a filter v2",
  "filters/Create a filter",
  "filters/Delete a filter v2",
  "filters/Edit a keyword within a filter v2",
  "filters/Remove a filter",
  "filters/Remove a status from a filter group v2",
  "filters/Remove keywords from a filter v2",
  "filters/Update a filter v2",
  "filters/Update a filter",
  "filters/View a single filter",
  "filters/View a single keyword v2",
  "filters/View a single status filter v2",
  "filters/View a specific filter v2",
  "filters/View all filters v2",
  "filters/View all status filters v2",
  "filters/View keywords added to a filter v2",
  "filters/View your filters",
  "followed_tags/View all followed tags",
  "follow_requests/Accept follow request",
  "follow_requests/Reject follow request",
  "follow_requests/View pending follow requests",
  "instance/(DEPRECATED) View server information (V1)",
  "instance/List of connected domains",
  "instance/List of rules",
  "instance/View extended description",
  "instance/View moderated servers",
  "instance/View server information",
  "instance/Weekly activity",
  "lists/Add accounts to a list",
  "lists/Create a list",
  "lists/Delete a list",
  "lists/Remove accounts from list",
  "lists/Show a single list",
  "lists/Update a list",
  "lists/View accounts in a list",
  "lists/View your lists",
  "markers/Get saved timeline positions",
  "markers/Save your position in a timeline",
  "media/(DEPRECATED) Upload media as an attachment",
  "media/Get media attachment",
  "media/Update media attachment",
  "media/Upload media as an attachment (async)",
  "mutes/View muted accounts",
  "notifications/(REMOVED) Dismiss a single notification",
  "notifications/Dismiss a single notification",
  "notifications/Dismiss all notifications",
  "notifications/Get a single notification",
  "notifications/Get all notifications",
  "oauth/Authorize a user",
  "oauth/Obtain a token",
  "oauth/Revoke a token",
  "polls/View a poll",
  "polls/Vote on a poll",
  "preferences/View user preferences",
  "profile/Delete profile avatar",
  "profile/Delete profile header",
  "push/Change types of notifications",
  "push/Get current subscription",
  "push/Remove current subscription",
  "push/Subscribe to push notifications",
  "reports/File a report",
  "scheduled_statuses/Cancel a scheduled status",
  "scheduled_statuses/Update a scheduled status’s publishing date",
  "scheduled_statuses/View a single scheduled status",
  "scheduled_statuses/View scheduled statuses",
  "search/(REMOVED) Search results (v1)",
  "search/Perform a search",
  "statuses/(DEPRECATED) Fetch preview card",
  "statuses/Bookmark a status",
  "statuses/Boost a status",
  "statuses/Delete a status",
  "statuses/Edit a status",
  "statuses/Favourite a status",
  "statuses/Get parent and child statuses in context",
  "statuses/Mute a conversation",
  "statuses/Pin status to profile",
  "statuses/Post a new status",
  "statuses/See who boosted a status",
  "statuses/See who favourited a status",
  "statuses/Translate a status",
  "statuses/Undo bookmark of a status",
  "statuses/Undo boost of a status",
  "statuses/Undo favourite of a status",
  "statuses/Unmute a conversation",
  "statuses/Unpin status from profile",
  "statuses/View a single status",
  "statuses/View edit history of a status",
  "statuses/View status source",
  "suggestions/(DEPRECATED) View follow suggestions (v1)",
  "suggestions/Remove a suggestion",
  "suggestions/View follow suggestions (v2)",
  "tags/Follow a hashtag",
  "tags/Unfollow a hashtag",
  "tags/View information about a single tag",
  "timelines/(DEPRECATED) View direct timeline",
  "timelines/View hashtag timeline",
  "timelines/View home timeline",
  "timelines/View list timeline",
  "timelines/View public timeline",
  "trends/View trending links",
  "trends/View trending statuses",
  "trends/View trending tags",
]